const userRole = {
  ROLE_USER: "ROLE_USER",
  ROLE_NOT_PERMITTED_TEACHER: "ROLE_NOT_PERMITTED_TEACHER",
  ROLE_TEACHER: "ROLE_TEACHER",
  ROLE_NOT_PERMITTED_DIRECTOR: "ROLE_NOT_PERMITTED_DIRECTOR",
  ROLE_DIRECTOR: "ROLE_DIRECTOR",
  ROLE_ADMIN: "ROLE_ADMIN",
};

export default userRole;
